name: Mayrav Herman
favicon: null
layout_spectrum: 0.11665
typography_spectrum: 0.73003
title: Mayrav Herman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#e2b9b9'
    - '#6f6f6f'
    - '#2f2f2f'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
