name: Mayrav Herman
favicon: null
layout_spectrum: 0.2497
typography_spectrum: 0.73003
title: Mayrav Herman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#e2b9b9'
    - '#010101'
    - '#848484'
  brandStrength: 0.8125
  lightness: 0.9744056309573352
  saturation: 0.8125
  rhythmicContrast: 0.26647944236174226
purpose: []
